version: "3.5"
services:
  ff_intg:
    container_name: "ff_intg"
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgresql
      - rabbitmq
    ports:
      - 8181:8181
    env_file:
      - .env.docker
    environment:
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672/
      DATABASE_URL: jdbc:postgresql://postgresql:5432/ff_db?sslmode=disable
      DATABASE_USER: ff_intg
      DATABASE_PASSWORD: ff_intg
    networks:
      - ff-network

  postgresql:
    container_name: postgresql
    environment:
      POSTGRES_DB: ff_db
      POSTGRES_PASSWORD: ff_intg
      POSTGRES_USER: ff_intg
    image: postgres:14-alpine
    networks:
      - ff-network
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - ff-network

  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_DB=ff_db
      - POSTGRES_USER=ff_intg
      - POSTGRES_PWD=ff_intg
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=false
    image: temporalio/auto-setup:latest
    networks:
      - ff-network
    ports:
      - 7233:7233
    labels:
      kompose.volume.type: configMap
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:latest
    networks:
      - ff-network
    stdin_open: true
    tty: true
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:latest
    networks:
      - ff-network
    ports:
      - 8080:8080

#  elasticsearch:
#    container_name: temporal-elasticsearch
#    environment:
#      - cluster.routing.allocation.disk.threshold_enabled=true
#      - cluster.routing.allocation.disk.watermark.low=512mb
#      - cluster.routing.allocation.disk.watermark.high=256mb
#      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
#      - discovery.type=single-node
#      - ES_JAVA_OPTS=-Xms256m -Xmx256m
#      - xpack.security.enabled=false
#    image: elasticsearch:${ELASTICSEARCH_VERSION}
#    networks:
#      - ff-network
#    expose:
#      - 9200
#    volumes:
#      - /var/lib/elasticsearch/data
networks:
  ff-network:
    driver: bridge
    name: ff-network